from django.conf.urls import patterns, url

urlpatterns = patterns('',
                       url(r'^users/name/(?P<name>\w+)', 'rest_api.views.search_users_by_name'),
                       url(r'^users/all$', 'rest_api.views.get_users'),
                       url(r'^users/(?P<id>\d+)', 'rest_api.views.get_user_by_id'),
                       url(r'^books/all', 'rest_api.views.get_ouvrages'),
                       url(r'^books/title/(?P<title>\w+)', 'rest_api.views.search_ouvrage_by_title'),
                       url(r'^books/editor/(?P<editor>\w+)', 'rest_api.views.search_ouvrage_by_editor'),
                       url(r'^books/search/(?P<query>((\w+)=(\w+)(&?))+)', 'rest_api.views.search_ouvrage_all'),
                       url(r'^books/(?P<id>\w+)', 'rest_api.views.get_ouvrage_by_id'),                       
                       url(r'^editors/name/(?P<name>\w+)', 'rest_api.views.search_editors_by_name'),
                       url(r'^editors/all$', 'rest_api.views.get_editors'),
                       url(r'^authors/name/(?P<name>\w+)', 'rest_api.views.search_auteurs_by_name'),
                       url(r'^authors/all$', 'rest_api.views.get_auteurs'),
                       url(r'^categories/name/(?P<name>\w+)', 'rest_api.views.search_categories_by_name'),
                       url(r'^categories/all$', 'rest_api.views.get_categories'),
                       url(r'^categories/(?P<prefix>\d+)', 'rest_api.views.get_categories_by_prefix'),
                       url(r'^series/name/(?P<name>\w+)', 'rest_api.views.search_series_by_name'),
                       url(r'^series/all$', 'rest_api.views.get_series'),
                       url(r'^series/categorie/(?P<categorie_id>\d+)', 'rest_api.views.search_series_by_categorie'),
                       url(r'^series/(?P<id>\d+)', 'rest_api.views.get_serie_by_id'),
                       url(r'^authenticate/salt', 'rest_api.views.get_salt'),
                       url(r'^authenticate', 'rest_api.views.authenticate'),
                       url(r'^emprunts/history/all', 'rest_api.views.get_emprunts_history'),
                       url(r'^emprunts/history/user/(?P<user_id>\d+)', 'rest_api.views.search_emprunts_history_by_user'),
                       url(r'^emprunts/history/book/(?P<cote>\d+)', 'rest_api.views.search_emprunts_history_by_book'),
                       url(r'^emprunts/history/serie/(?P<serie_id>\d+)', 'rest_api.views.search_emprunts_history_by_serie'),
                       url(r'^postes/all', 'rest_api.views.get_postes'),
                       url(r'^postes/(?P<id>\d+)', 'rest_api.views.get_poste_by_id'),
                       url(r'^actifs/all', 'rest_api.views.get_actifs'),
                       url(r'^actifs/(?P<id>\d+)', 'rest_api.views.get_actif_by_id'),
                       url(r'^plans/all', 'rest_api.views.get_plans'),
                       url(r'^plans/(?P<id>\d+)', 'rest_api.views.get_plan_by_id'),
                       url(r'^abonnements/all', 'rest_api.views.get_abonnements'),
                       url(r'^abonnements/(?P<id>\d+)', 'rest_api.views.get_abonnement_by_id'),
                       url(r'^emprunts/return', 'rest_api.views.return_book'),
                       url(r'^emprunts/all', 'rest_api.views.get_emprunts')
                      )
